/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.etherealhazel.spring.core.demo.app;

import com.etherealhazel.spring.core.demo.app.domain.Human;

public class App {
    public static void main(String[] args) {
        
        Human human = new Human();
        
        human.goOutside();
  
    }
}
