/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.etherealhazel.spring.core.demo.app;

import com.etherealhazel.spring.core.demo.app.domain.BlueJeans;
//import com.etherealhazel.spring.core.demo.app.domain.CargoPants;
import com.etherealhazel.spring.core.demo.app.domain.Human;
import com.etherealhazel.spring.core.demo.app.domain.Pants;

//The issue now is that we still need to maintain the lifecycle
//of the pants objects here in the main method.

public class App {
    public static void main(String[] args) {
        
        Pants bluejeans = new BlueJeans();
        //Pants cargoPants = new CargoPants();

        Human human = new Human();
        human.setPants(bluejeans);
        
        human.goOutside();    
  
    }
}
