/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * https://www.vojtechruzicka.com/field-dependency-injection-considered-harmful/
 */
package com.etherealhazel.spring.core.demo.app;

import com.etherealhazel.spring.core.demo.app.config.AppConfig;
import com.etherealhazel.spring.core.demo.app.domain.Human;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {
    public static void main(String[] args) {

        AnnotationConfigApplicationContext applicationContext = 
        new AnnotationConfigApplicationContext(AppConfig.class);
        
        Human human = applicationContext.getBean("human", Human.class);
        
        human.goOutside();    
  
        applicationContext.close();
        
    }
}
